version: '2'

services:
    mongodata:
        image: mongo:3.2
        volumes:
        - /data/db
        entrypoint: /bin/bash
    mongo:
        image: mongo:3.2
        depends_on: 
            - mongodata
        volumes_from:
            - mongodata
        ports:
            - "27017"
    web:	
      image: rest-api
        depends_on: 
            - mongo
        environment:
            - MONGODB_DB_NAME=estabelecimentos
        ports:
            - "8080"
        links:
            - mongo
      		

	  lb:
	    image: dockercloud/haproxy
	    ports:
	      - 80:80
	    links:
	      - web
	    networks:
	      - front-tier
	      - back-tier
	    volumes:
	      - /var/run/docker.sock:/var/run/docker.sock 

	networks:
	  front-tier:
	    driver: bridge
	  back-tier:
	    driver: bridge